---
- name: Install and configure tomcat server for deployment
  hosts: nodes
  remote_user: root

  vars:
    tomcat_user: tomcat
    tomcat_path: /opt/tomcat

  tasks:
    - name: Update system package
      apt:
#        state: latest
        upgrade: yes
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Tomcat User
      user:
        name: {{tomcat_user}}

    - name: Create Tomcat Group
      group:
        name: tomcat

    - name: Create Tomcat Directory
      file:
        path: {{ tomcat_path }}
        owner: {{ tomcat_user }}
        group: {{ tomcat_user }}
        mode: 755
        recurse: yes

    - name: Download Tomcat and unarchive
      unarchive:
         src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.72//bin/apache-tomcat-9.0.72.tar.gz
         dest: {{ tomcat_path }}
         remote_src: yes
         extra_opts: [--strip-components=1]

    - name: Start tomcat server
      command: sh /opt/tomcat/bin/startup.sh

    - name: allow tcp connections
      command: sudo ufw allow 8080/tcp

